version: '3'
services:
  db:
    image: postgres:alpine
    container_name: postgresdb
    hostname: db
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASS}
      - POSTGRES_DB=${DATABASE_NAME}
    restart: unless-stopped
    ports:
      - 5432:5432
    networks:
      - connection
  
  app:
    container_name: be-project
    environment:
      - APP_HOST=${APP_HOST}
      - APP_PORT=${APP_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_PASS=${DATABASE_PASS}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - SANDBOX_CLIENT=${SANDBOX_CLIENT}
      - SANDBOX_SERVER=${SANDBOX_SERVER}
      - PRODUCTION_CLIENT=${PRODUCTION_CLIENT}
      - PRODUCTION_SERVER=${PRODUCTION_SERVER}
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 45000:45000
    volumes:
      - ./app
    depends_on:
      - db
    networks:
      - connection

networks:
  connection:
    driver: bridge