version: '3'
services:
  app:
    container_name: be-project
    environment:
      - APP_HOST=${APP_HOST}
      - APP_PORT=${APP_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_PASS=${DATABASE_PASS}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - 45000:45000
    volumes:
      - ./app
    depends_on:
      - postgresdb
    networks:
      - connection
  
  postgresdb:
    image: postgres:latest
    container_name: db-be
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASS}
      - POSTGRES_DB=${DATABASE_NAME}
      - DATABASE_HOST=${DATABASE_HOST}
    restart: always
    ports:
      - 5432:532
    networks:
      - connection

networks:
  connection:
    driver: bridge